version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: bomb-mailer-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  # bomb-mailer-api service
  bomb-mailer-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: bomb-mailer-api
    depends_on:
      - mongo
    ports:
      - "${BOMB_MAILER_API_PORT}:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${BOMB_MAILER_API_PORT}
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
    links:
      - mongo
    volumes:
      - ./api:/usr/src/app